# Generated by Django 5.2.4 on 2025-07-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_panel', '0002_medicine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
