# Generated by Django 5.2.4 on 2025-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_panel', '0004_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, choices=[('Antibiotic', 'Antibiotic'), ('Painkiller', 'Painkiller'), ('Antiseptic', 'Antiseptic'), ('Supplement', 'Supplement')], max_length=50, null=True),
        ),
    ]
