# Generated by Django 5.2.4 on 2025-07-22 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_doctor_user'),
        ('pharmacist_panel', '0005_alter_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
            preserve_default=False,
        ),
    ]
