# Generated by Django 5.2.4 on 2025-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_panel', '0006_prescription_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
