# Generated by Django 5.2.4 on 2025-07-22 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_panel', '0008_dispensationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient_or_ward', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist_panel.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='WastageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist_panel.medicine')),
            ],
        ),
    ]
