# Generated by Django 5.2.4 on 2025-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Medicine', 'Medicine'), ('Lab', 'Lab')], max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
