# Generated by Django 5.2 on 2025-07-18 23:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_enquiry_created_at_enquiry_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(to='core.User', on_delete=models.CASCADE, null=True),

            preserve_default=False,
        ),
    ]
