# Generated by Django 5.2.4 on 2025-07-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_doctor_appointments_completed_doctor_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointments_completed',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='start_price',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
