# Generated by Django 5.2.4 on 2025-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_doctor_appointments_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointments_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
