# Generated by Django 5.2.4 on 2025-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_doctor_appointments_completed_doctor_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
