# Generated by Django 5.2.4 on 2025-07-31 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_attendance_shift_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient'),
        ),
    ]
