# Generated by Django 5.2 on 2025-08-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bed_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
