# Generated by Django 5.2 on 2025-08-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_appointment_sender_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
