# Generated by Django 5.2 on 2025-08-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_appointment_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_read',
        ),
    ]
