# Generated by Django 5.2 on 2025-08-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('walk-in', 'Walk-in'), ('referral', 'Referral'), ('ads', 'Advertisement'), ('online', 'Online Search'), ('other', 'Other')], default='walk-in', max_length=50, null=True),
        ),
    ]
