# Generated by Django 5.2 on 2025-08-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_patient_referral_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(choices=[('walk-in', 'Walk-in'), ('referral', 'Referral'), ('ads', 'Advertisement'), ('online', 'Online Search'), ('other', 'Other')], max_length=50),
        ),
    ]
