# Generated by Django 5.2.4 on 2025-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_patient_referral_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(choices=[('walk-in', 'Walk-in'), ('referral', 'Referral'), ('online', 'Online Search'), ('ads', 'Advertisement'), ('other', 'Other')], max_length=20),
        ),
    ]
