# Generated by Django 5.1.11 on 2025-08-07 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentreminder',
            options={'ordering': ['-reminder_sent_at'], 'verbose_name': 'Appointment Reminder', 'verbose_name_plural': 'Appointment Reminders'},
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='reminder_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
