# Generated by Django 5.1.11 on 2025-08-07 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_appointment_location_appointment_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 11, 47, 56, 503655)),
            preserve_default=False,
        ),
    ]
