# Generated by Django 5.2 on 2025-08-16 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0036_delete_patientnote'),
        ('core', '0053_patientnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientnote',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='patientnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.invoice'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
