# Generated by Django 5.2 on 2025-08-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_patientnote_options_patientnote_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientnote',
            name='invoice',
        ),
    ]
