# Generated by Django 5.1.11 on 2025-08-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_patientnote_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency'), ('Walk-in', 'Walk-in')], default='Regular', max_length=20),
        ),
    ]
