# Generated by Django 5.1.11 on 2025-08-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(choices=[('walk-in', 'Walk-in'), ('referral', 'Referral'), ('ads', 'Advertisement'), ('online', 'Online Search'), ('doctor', 'Doctor'), ('other', 'Other')], max_length=20),
        ),
    ]
