# Generated by Django 5.2 on 2025-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_patient_referrer_patient_registered_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='referrer',
            new_name='referred_by',
        ),
        migrations.AddField(
            model_name='patient',
            name='referral_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(choices=[('walk-in', 'Walk-in'), ('referral', 'Referral'), ('ads', 'Advertisement'), ('online', 'Online Search'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab', 'Lab Technician'), ('other', 'Other')], default='walk-in', max_length=30),
        ),
    ]
