# Generated by Django 5.2 on 2025-08-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_rename_referrer_patient_referred_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(choices=[('walk-in', 'Walk-in'), ('advertisement', 'Advertisement'), ('online', 'Online Search'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('labtech', 'Lab Technician'), ('other', 'Other')], default='walk-in', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('labtech', 'Lab Technician'), ('patient', 'Patient'), ('cashier', 'Cashier')], default='patient', max_length=20),
        ),
    ]
