# Generated by Django 5.2 on 2025-07-18 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=100)),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab Test'), ('surgery', 'Surgery'), ('pharmacy', 'Pharmacy'), ('others', 'Other Services')], max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS (Card)'), ('bank_transfer', 'Bank Transfer'), ('mobile', 'Mobile Payment'), ('insurance', 'Insurance')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
