# Generated by Django 5.2 on 2025-07-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_alter_refund_approved_by'),
        ('core', '0023_refundrequest_admin_note_refundrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient_dob',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
            preserve_default=False,
        ),
    ]
