# Generated by Django 5.2 on 2025-07-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_alter_invoice_options_invoice_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient_dob',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient_name',
        ),
    ]
