# Generated by Django 5.2 on 2025-07-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0016_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
