# Generated by Django 5.1.11 on 2025-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0018_alter_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('surgery', 'Surgery'), ('pharmacy', 'Pharmacy'), ('lab', 'Lab Test'), ('radiology', 'Radiology')], default='consultation', max_length=50),
        ),
    ]
