# Generated by Django 5.1.11 on 2025-08-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0020_alter_payment_service_type'),
        ('core', '0049_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment'),
        ),
    ]
