# Generated by Django 5.1.11 on 2025-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0021_payment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('surgery', 'Surgery'), ('lab', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('admission', 'Admission'), ('appointment', 'Appointment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
