# Generated by Django 5.2 on 2025-08-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0022_alter_payment_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Automatically flagged as overdue by the system'),
        ),
    ]
