# Generated by Django 5.2 on 2025-08-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0024_alter_payment_reference_number'),
        ('core', '0051_failedloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.patient'),
        ),
    ]
