# Generated by Django 5.2 on 2025-08-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0025_alter_invoice_patient'),
        ('core', '0051_failedloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.patient'),
        ),
    ]
