# Generated by Django 5.2 on 2025-08-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0026_alter_payment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab Test'), ('surgery', 'Surgery'), ('pharmacy', 'Pharmacy'), ('appointment', 'Appointment'), ('others', 'Other Services')], max_length=50),
        ),
    ]
