# Generated by Django 5.1.11 on 2025-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0028_invoice_amount_paid_invoice_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('refund_approval', 'Pending Refund/Adjustment Approval'), ('large_balance', 'Patient with Large Outstanding Balance'), ('invoice_discrepancy', 'Invoice Discrepancy or Error')], max_length=50)),
                ('description', models.TextField(help_text='Details about the alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
