# Generated by Django 5.1.11 on 2025-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0029_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
