# Generated by Django 5.2 on 2025-08-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0030_alter_refund_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(default='Insurance & Third-Party Payer Information', max_length=255)),
                ('body', models.TextField(blank=True, default='Show insurance coverage details if applicable\n\nIndicate which payments are made by insurance and which are patient out-of-pocket\n\nWhy: Many hospitals work with insurance; cashiers need to track these separately.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Section',
                'verbose_name_plural': 'Dashboard Sections',
            },
        ),
    ]
