# Generated by Django 5.1.11 on 2025-08-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0033_adjustmenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdjustmentHistory',
        ),
    ]
