# Generated by Django 5.1.11 on 2025-08-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0036_delete_patientnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Currency code (e.g. USD, EUR, NGN)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Full name of the currency', max_length=50)),
                ('symbol', models.CharField(help_text='Symbol (e.g. $, €, ₦)', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Rate against base currency (e.g. 1 USD = X Local Currency)', max_digits=10)),
                ('is_base', models.BooleanField(default=False, help_text='Mark only ONE as base currency')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
