# Generated by Django 5.1.11 on 2025-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0039_usersessionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
    ]
