# Generated by Django 5.2 on 2025-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_month', models.DateField()),
                ('expected_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CostPerPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_patients', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insurer', models.CharField(max_length=100)),
                ('date_submitted', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueAging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_reference', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
