# Generated by Django 5.2 on 2025-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueaging',
            name='bill_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
