# Generated by Django 5.2 on 2025-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_revenueaging_bill_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueaging',
            name='bill_reference',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
