# Generated by Django 5.2 on 2025-08-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_revenueaging_bill_reference'),
        ('core', '0037_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenueaging',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='revenueaging',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.AlterField(
            model_name='revenueaging',
            name='bill_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
