# Generated by Django 5.2 on 2025-08-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_revenueaging_patient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('importance', models.TextField(help_text='Explain why this feature matters.')),
            ],
        ),
    ]
