# Generated by Django 5.2 on 2025-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_kpitracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('readmission', 'Readmission Rates'), ('infection', 'Infection/Complication Rates'), ('outcomes', 'Treatment Outcome Trends')], max_length=50, unique=True)),
                ('description', models.TextField(help_text='Why this metric matters')),
                ('value', models.CharField(help_text='Current metric value (e.g. 12%, 3 per 1000, etc.)', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
