# Generated by Django 5.2 on 2025-08-06 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_clinicalmetric'),
        ('core', '0043_alter_patient_referral_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalComplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complication_type', models.CharField(max_length=100)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complications', to='core.admission')),
            ],
        ),
    ]
