# Generated by Django 5.2 on 2025-08-06 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_clinicalcomplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalcomplication',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
