# Generated by Django 5.1.11 on 2025-08-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_clinicalcomplication_reported_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowforecast',
            name='expected_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashflowforecast',
            name='expected_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
