# Generated by Django 5.1.11 on 2025-08-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_cashflowforecast_expected_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitracking',
            name='value',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
