# Generated by Django 5.2 on 2025-08-09 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_kpitracking_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_type', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('email_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
            ],
            options={
                'verbose_name': 'Automation Settings',
                'verbose_name_plural': 'Automation Settings',
            },
        ),
        migrations.CreateModel(
            name='LowInventoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('threshold', models.IntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(blank=True, null=True)),
                ('sms_recipients', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverduePaymentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days_overdue', models.IntegerField(default=30)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('flag_reason', models.CharField(default='Overdue payment', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSchedulingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_future_days', models.IntegerField(default=7)),
                ('enabled', models.BooleanField(default=True)),
                ('rotation_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
