# Generated by Django 5.1.11 on 2025-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_paymentmodereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueaging',
            name='service_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('consultation', 'Consultation'), ('surgery', 'Surgery'), ('pharmacy', 'Pharmacy'), ('lab', 'Lab Test'), ('admission', 'Admission'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
