"""
Django settings for hospital_mgmt project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-piori(yx1*2!xl#!_80!pmm66-)i9^$issbv&znd+3er+mtwg*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'admin_panel',
    'doctor_panel',
    'nurse_panel',
    'receptionist_panel',
    'pharmacist_panel',
    'labtech_panel',
    'patient_panel',
    'cashier',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'django.contrib.humanize',
    'django_cron',
  

  
    
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hospital_mgmt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.header_settings',
                'core.context_processors.footer_settings',
                'core.context_processors.appointment_form_processor',
                'core.context_processors.unread_message_context', 
                'core.context_processors.footer_form',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'hospital_mgmt.wsgi.application'

# 💱 Dummy Exchange Rates (Test Data)
EXCHANGE_RATES = {
    "USD": {"symbol": "$", "rate": 1.00, "is_base": True},
    "EUR": {"symbol": "€", "rate": 0.92},
    "GBP": {"symbol": "£", "rate": 0.78},
    "NGN": {"symbol": "₦", "rate": 1500.00},
    "KES": {"symbol": "KSh", "rate": 130.00},
    "GHS": {"symbol": "₵", "rate": 15.50},
    "ZAR": {"symbol": "R", "rate": 19.00},
    "CAD": {"symbol": "C$", "rate": 1.34},
    "AUD": {"symbol": "A$", "rate": 1.52},
    "CNY": {"symbol": "¥", "rate": 7.10},
    "JPY": {"symbol": "¥", "rate": 145.00},
    "INR": {"symbol": "₹", "rate": 83.20},
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CRON_CLASSES = [
    "admin_panel.cron.UpdateClinicalMetricsCronJob",
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MIDDLEWARE += [
    'core.middleware.AccessLogMiddleware',
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'NewLifeClinic12190@outlook.com'
EMAIL_HOST_PASSWORD = '3#Axa7K!cTT5YnK'  # Use app password if Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# settings.py
LOGIN_URL = '/login/'





# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

