# Generated by Django 5.2 on 2025-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_panel', '0003_alter_bill_patient_alter_diagnosis_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='seen_by_doctor_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
