# Generated by Django 5.1.11 on 2025-08-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_appointment_appointment_type'),
        ('doctor_panel', '0002_medicalrecord_imaging_medicalrecord_lab_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='aappointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='core.appointment'),
        ),
    ]
