# Generated by Django 5.1.11 on 2025-08-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_panel', '0003_medicalrecord_aappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='aappointment',
            new_name='appointment',
        ),
    ]
