# Generated by Django 5.1.11 on 2025-08-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_panel', '0004_rename_aappointment_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='imaging',
            field=models.ImageField(blank=True, null=True, upload_to='medical_images/'),
        ),
    ]
