# Generated by Django 5.1.11 on 2025-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_panel', '0007_diagnostictest_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_insurance',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
