# Generated by Django 5.1.11 on 2025-08-20 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_patient_doctor'),
        ('doctor_panel', '0009_patientportalrequest_referralrequest_staffmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_tests', to='core.patient'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='core.patient'),
        ),
        migrations.AddField(
            model_name='patientportalrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_requests', to='core.patient'),
        ),
        migrations.AddField(
            model_name='patientportalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.patient'),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_tests', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='patientportalrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='referralrequest',
            name='from_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='referralrequest',
            name='to_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='staffmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_messages_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
