# Generated by Django 5.1.11 on 2025-08-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_patient_referral_source'),
        ('doctor_panel', '0010_remove_interaction_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrequest',
            name='from_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='core.doctor'),
        ),
    ]
