# Generated by Django 5.1.11 on 2025-08-21 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_patient_referral_source'),
        ('doctor_panel', '0011_alter_referralrequest_from_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrequest',
            name='to_lab_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='to_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='to_pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacist_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralrequest',
            name='to_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='core.doctor'),
        ),
    ]
