# Generated by Django 5.1.11 on 2025-08-21 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_panel', '0012_referralrequest_to_lab_tech_referralrequest_to_nurse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrequest',
            name='from_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent_by_lab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='from_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent_by_nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='from_pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent_by_pharmacist', to=settings.AUTH_USER_MODEL),
        ),
    ]
