# Generated by Django 5.2 on 2025-08-24 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_panel', '0013_referralrequest_from_lab_referralrequest_from_nurse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralrequest',
            name='from_doctor',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='from_lab',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='from_nurse',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='from_pharmacist',
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
