# Generated by Django 5.2 on 2025-08-25 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_patient_referral_source_alter_user_role'),
        ('doctor_panel', '0014_remove_referralrequest_from_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralrequest',
            name='to_lab_tech',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='to_nurse',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='to_pharmacist',
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralrequest',
            name='to_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_referrals', to='core.doctor'),
        ),
    ]
