# Generated by Django 5.1.11 on 2025-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_panel', '0015_remove_referralrequest_to_lab_tech_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Analytics Config', max_length=120)),
                ('show_patient_counts', models.BooleanField(default=True)),
                ('show_case_mix', models.BooleanField(default=True)),
                ('show_outcomes', models.BooleanField(default=True)),
                ('show_revenue', models.BooleanField(default=False)),
                ('default_date_range', models.CharField(choices=[('day', 'Today'), ('week', 'This week'), ('month', 'This month'), ('quarter', 'This quarter')], default='day', max_length=10)),
                ('followup_rate_threshold', models.FloatField(default=0.6, help_text='If follow-up rate < this, show alert')),
                ('revenue_enabled', models.BooleanField(default=False, help_text='Enable revenue metrics (if you store billing data)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics configuration',
                'verbose_name_plural': 'Analytics configurations',
            },
        ),
    ]
