# Generated by Django 5.2.4 on 2025-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtech_panel', '0002_labtestrequest_attachment_labtestrequest_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
