# Generated by Django 5.2.4 on 2025-07-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyround',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
